'''
# --------------------------------------------------
# Clipboard
# --------------------------------------------------

#bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# --------------------------------------------------
# Shell
# --------------------------------------------------

#set -g default-shell /bin/bash
set -g default-shell /usr/bin/zsh
# --------------------------------------------------
# Prefix
# --------------------------------------------------

set -g prefix C-a
unbind C-b
bind C-a send-prefix

# --------------------------------------------------
# Mouse / Copy Mode
# --------------------------------------------------

set -g mouse on
setw -g mode-keys vi

# --------------------------------------------------
# Theme
# --------------------------------------------------

# Terminal capabilities
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',*:Tc'

# Status bar
set -g status-style bg=#11161C,fg=#C7CDD6
set -g status-position top
set -g status-justify centre

# Left
set -g status-left-length 25
set -g status-left "#[fg=#FF404D,bold] #S "

# Right
set -g status-right-length 40
set -g status-right "#[fg=#FF404D] void ✦ execute ⚡ "

# Inactive windows
set -g window-status-format "#[fg=#7A8492,bg=#11161C] #I "

# Active window
set -g window-status-current-format "#[fg=#0B0D10,bg=#FF404D,bold] #I "

# Space between tabs
set -g window-status-separator " "

# Pane borders
set -g pane-border-style fg=#2A313B
set -g pane-active-border-style fg=#FF404D

# Copy mode
#set -g mode-style "bg=#FF404D,fg=#0B0D10,bold"
set -g mode-style "bg=yellow,fg=black,bold"
# Messages
set -g message-style bg=#FF404D,fg=#0B0D10

# --------------------------------------------------
# History
# --------------------------------------------------

set -g history-limit 100000

# --------------------------------------------------
# Logging
# --------------------------------------------------

run-shell /opt/tmux-logging/logging.tmux

# --------------------------------------------------
# Windows
# --------------------------------------------------

set -g automatic-rename on

bind c new-window -c "#{pane_current_path}"

# --------------------------------------------------
# Splits
# --------------------------------------------------

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

unbind '"'
unbind %

'''
